version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      
  - package-ecosystem: "docker"
    directory: "infra/docker/php"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
