services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - ENV=${ENV:-local}
      target: ${ENV:-local}
    volumes:
      - type: bind
        source: ./
        target: /src
      - type: bind
        source: ./infra/docker/php/php.ini/php.${ENV:-local}.ini
        target: /usr/local/etc/php/php.ini
    ports:
      - "80:80"
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]
